name: CICD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  compile:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Check Java Version
        run: |
          java -version
          mvn -version

      - name: Resolve Maven Dependencies
        run: mvn dependency:resolve

      - name: Build with Maven
        run: mvn clean compile


  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Check Java and Maven Version
        run: |
          java -version
          mvn -version

      - name: Resolve Maven Dependencies
        run: mvn dependency:resolve

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "json"
          output: "fs-report.json"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: fs-report.json
